spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: bigff

logging:
  level:
    root: info
    com.bigff.blog: debug
  file:
    name: log/blog-dev.log

server:
  port: 8888

mybatis:
  type-aliases-package: com.bigff.blog.entity
  mapper-locations: classpath*:mapper/*.xml
