spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog??useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: bigff

logging:
  level:
    root: info
    com.bigff.blog: debug
  file:
    name: log/blog-dev.log

server:
  port: 8888

mybatis:
  type-aliases-package: com.bigff.blog.entity
  mapper-locations: classpath*:mapper/*.xml
  table:
    auto: update
    model:
      pack: com.bigff.blog.entity #扫描用于创建表的对象的包名
    database:
      type: mysql
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


